### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by AvinashReddy3108** [AvinashReddy3108/PaperplaneRemix#19]
As the title says, these are some of the things that I have planned for this project
PS: the items are not in order, I'm lazy lol

- [x] **BREAKING CHANGE**: Move from `dill` to `msgpack` (for speed and security)
- [x] Moving `Dockerfile` to Python 3.10.x (the packages given below are having issues being installed in 3.10.x)
	- [x] ~[pyaesni](https://pypi.org/project/pyaesni)~ (replaced with `telethon-tgcrypto`)
	- [x] ~[cchardet](https://pypi.org/project/cchardet)~ (requires `g++` installed)
- [ ] Kanging video stickers (but avoiding ffmpeg calls using `os.system` as many others have done)
- [ ] Move to organization, gut modules away from core (Magisk like module organization)
- [ ] d o c u m e n t a t i o n
- [ ] Notes & filters (same as the group admin bots)
- [ ] Snips (personal notes)
